#!/usr/bin/env bash
set -euo pipefail

REPO_OWNER="${REPO_OWNER:-Aux0x7F}"
REPO_NAME="${REPO_NAME:-constitute-gateway}"
SETUP_TIMER=0
# Production-safe default. Keep this moderate to avoid noisy release polling.
TIMER_INTERVAL="${TIMER_INTERVAL:-30m}"
# Development profile: intentionally short poll interval for rapid release iteration.
DEV_TIMER_INTERVAL="${DEV_TIMER_INTERVAL:-2m}"
DEV_POLL=0
INSTALL_DIR="/usr/local/lib/constitute-gateway"
UPDATER_SCRIPT="${INSTALL_DIR}/update-from-github.sh"
TIMER_UNIT="constitute-gateway-update.timer"
SERVICE_UNIT="constitute-gateway-update.service"
CURL_PROXY_URL="${CURL_PROXY_URL:-}"
USE_TOR=0
TOR_SOCKS_ADDR="${TOR_SOCKS_ADDR:-127.0.0.1:9050}"
TOR_CONTROL_ADDR="${TOR_CONTROL_ADDR:-127.0.0.1:9051}"
TOR_ROTATE_ON_RETRY=1
PAIR_IDENTITY=""
PAIR_CODE=""
PAIR_CODE_HASH=""

usage() {
  cat <<'EOF'
Usage: install-latest.sh [options]

Install or update constitute-gateway Linux artifact from GitHub Releases.

Options:
  --repo-owner <owner>       GitHub owner (default: Aux0x7F)
  --repo-name <name>         GitHub repo (default: constitute-gateway)
  --pair-identity <label>    Identity label for auto-associate pairing enrollment
  --pair-code <code>         One-time pairing code generated by web install flow
  --pair-code-hash <hash>    Pairing code hash override (optional)
  --setup-timer              Install and enable systemd timer for periodic updates
  --timer-interval <value>   systemd OnUnitActiveSec value (default: 30m)
  --dev-poll                 Use fast dev polling interval (default: 2m)
  --proxy-url <url>          Use HTTP(S) proxy for release fetches
  --tor                      Use Tor SOCKS egress for release fetches
  --tor-socks <host:port>    Tor SOCKS endpoint (default: 127.0.0.1:9050)
  --tor-control <host:port>  Tor control endpoint for optional NEWNYM (default: 127.0.0.1:9051)
  --no-tor-rotate            Disable NEWNYM attempt on retry
  -h, --help                 Show this help

Examples:
  ./scripts/linux/install-latest.sh
  ./scripts/linux/install-latest.sh --setup-timer --timer-interval 1h
  ./scripts/linux/install-latest.sh --setup-timer --dev-poll
  ./scripts/linux/install-latest.sh --setup-timer --tor --tor-socks 127.0.0.1:9050

Dev flow (local source build):
  git clone https://github.com/Aux0x7F/constitute-gateway.git
  cd constitute-gateway
  cargo build --release --features platform-linux
  sudo ./scripts/linux/install-service.sh \
    --binary ./target/release/constitute-gateway \
    --config-template ./config.example.json
EOF
}

run_sudo() {
  if [[ "$(id -u)" -eq 0 ]]; then
    "$@"
  else
    sudo "$@"
  fi
}

require_cmd() {
  local cmd="$1"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "Missing required command: $cmd" >&2
    exit 1
  fi
}

build_curl_args() {
  CURL_ARGS=(-fsSL)
  if [[ -n "$CURL_PROXY_URL" ]]; then
    CURL_ARGS+=(--proxy "$CURL_PROXY_URL")
  fi
  if [[ "$USE_TOR" -eq 1 ]]; then
    CURL_ARGS+=(--proxy "socks5h://${TOR_SOCKS_ADDR}")
  fi
}

rotate_tor_exit() {
  [[ "$USE_TOR" -eq 1 ]] || return 0
  [[ "$TOR_ROTATE_ON_RETRY" -eq 1 ]] || return 0
  command -v nc >/dev/null 2>&1 || return 0

  local host="${TOR_CONTROL_ADDR%:*}"
  local port="${TOR_CONTROL_ADDR##*:}"
  [[ -n "$host" && -n "$port" && "$host" != "$port" ]] || return 0

  {
    printf 'AUTHENTICATE\r\n'
    printf 'SIGNAL NEWNYM\r\n'
    printf 'QUIT\r\n'
  } | nc -w 2 "$host" "$port" >/dev/null 2>&1 || true
}

verify_tor_proxy() {
  [[ "$USE_TOR" -eq 1 ]] || return 0
  if ! curl "${CURL_ARGS[@]}" --max-time 12 -I https://github.com >/dev/null 2>&1; then
    echo "Tor proxy check failed at socks5h://${TOR_SOCKS_ADDR}" >&2
    exit 1
  fi
}

download_with_retry() {
  local url="$1"
  local out="$2"
  local attempt
  for attempt in 1 2 3; do
    if curl "${CURL_ARGS[@]}" "$url" -o "$out"; then
      return 0
    fi
    rotate_tor_exit
    sleep "$attempt"
  done
  return 1
}

setup_update_timer() {
  local persisted_args=(--repo-owner "$REPO_OWNER" --repo-name "$REPO_NAME")
  local persisted_args_str=""

  if [[ "$DEV_POLL" -eq 1 ]]; then
    persisted_args+=(--dev-poll)
  else
    persisted_args+=(--timer-interval "$TIMER_INTERVAL")
  fi
  if [[ -n "$CURL_PROXY_URL" ]]; then
    persisted_args+=(--proxy-url "$CURL_PROXY_URL")
  fi
  if [[ "$USE_TOR" -eq 1 ]]; then
    persisted_args+=(--tor --tor-socks "$TOR_SOCKS_ADDR" --tor-control "$TOR_CONTROL_ADDR")
  fi
  if [[ "$TOR_ROTATE_ON_RETRY" -eq 0 ]]; then
    persisted_args+=(--no-tor-rotate)
  fi

  printf -v persisted_args_str ' %q' "${persisted_args[@]}"

  run_sudo mkdir -p "$INSTALL_DIR"

  run_sudo tee "$UPDATER_SCRIPT" >/dev/null <<EOF
#!/usr/bin/env bash
set -euo pipefail
curl -fsSL "https://raw.githubusercontent.com/${REPO_OWNER}/${REPO_NAME}/main/scripts/linux/install-latest.sh" | bash -s --${persisted_args_str}
EOF
  run_sudo chmod 0755 "$UPDATER_SCRIPT"

  run_sudo tee "/etc/systemd/system/${SERVICE_UNIT}" >/dev/null <<EOF
[Unit]
Description=Constitute Gateway update check
Wants=network-online.target
After=network-online.target

[Service]
Type=oneshot
ExecStart=${UPDATER_SCRIPT}
EOF

  run_sudo tee "/etc/systemd/system/${TIMER_UNIT}" >/dev/null <<EOF
[Unit]
Description=Periodic Constitute Gateway update check

[Timer]
OnBootSec=10m
OnUnitActiveSec=${TIMER_INTERVAL}
RandomizedDelaySec=2m
Persistent=true

[Install]
WantedBy=timers.target
EOF

  run_sudo systemctl daemon-reload
  run_sudo systemctl enable --now "$TIMER_UNIT"
  run_sudo systemctl status "$TIMER_UNIT" --no-pager || true
}

patch_release_metadata() {
  local channel="$1"
  local track="$2"
  local branch="$3"
  local cfg_path="/etc/constitute-gateway/config.json"

  if [[ ! -f "$cfg_path" ]]; then
    return 0
  fi
  if ! command -v python3 >/dev/null 2>&1; then
    echo "python3 not found; skipping release metadata patch" >&2
    return 0
  fi

  run_sudo env CFG_PATH="$cfg_path" CFG_CHANNEL="$channel" CFG_TRACK="$track" CFG_BRANCH="$branch" python3 - <<'PY'
import json
import os
from pathlib import Path

path = Path(os.environ.get('CFG_PATH', '/etc/constitute-gateway/config.json'))
if not path.exists():
    raise SystemExit(0)

cfg = json.loads(path.read_text(encoding='utf-8'))
cfg['release_channel'] = os.environ.get('CFG_CHANNEL', 'release').strip() or 'release'
cfg['release_track'] = os.environ.get('CFG_TRACK', 'latest').strip() or 'latest'
cfg['release_branch'] = os.environ.get('CFG_BRANCH', '').strip()
path.write_text(json.dumps(cfg, indent=2) + '\n', encoding='utf-8')
PY
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo-owner)
      REPO_OWNER="${2:?missing value for --repo-owner}"
      shift 2
      ;;
    --repo-name)
      REPO_NAME="${2:?missing value for --repo-name}"
      shift 2
      ;;
    --setup-timer)
      SETUP_TIMER=1
      shift
      ;;
    --pair-identity)
      PAIR_IDENTITY="${2:?missing value for --pair-identity}"
      shift 2
      ;;
    --pair-code)
      PAIR_CODE="${2:?missing value for --pair-code}"
      shift 2
      ;;
    --pair-code-hash)
      PAIR_CODE_HASH="${2:?missing value for --pair-code-hash}"
      shift 2
      ;;
    --timer-interval)
      TIMER_INTERVAL="${2:?missing value for --timer-interval}"
      DEV_POLL=0
      shift 2
      ;;
    --dev-poll)
      DEV_POLL=1
      TIMER_INTERVAL="$DEV_TIMER_INTERVAL"
      shift
      ;;
    --proxy-url)
      CURL_PROXY_URL="${2:?missing value for --proxy-url}"
      shift 2
      ;;
    --tor)
      USE_TOR=1
      shift
      ;;
    --tor-socks)
      USE_TOR=1
      TOR_SOCKS_ADDR="${2:?missing value for --tor-socks}"
      shift 2
      ;;
    --tor-control)
      TOR_CONTROL_ADDR="${2:?missing value for --tor-control}"
      shift 2
      ;;
    --no-tor-rotate)
      TOR_ROTATE_ON_RETRY=0
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

require_cmd curl
require_cmd grep
require_cmd sha256sum
require_cmd tar
require_cmd bash
build_curl_args
verify_tor_proxy

BASE="https://github.com/${REPO_OWNER}/${REPO_NAME}/releases/latest/download"
LINUX_ASSET="constitute-gateway-linux-amd64.tar.gz"
SUMS_NAME="SHA256SUMS"

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

if ! download_with_retry "${BASE}/${LINUX_ASSET}" "${tmpdir}/${LINUX_ASSET}"; then
  echo "Failed to download ${LINUX_ASSET}" >&2
  exit 1
fi

if ! download_with_retry "${BASE}/${SUMS_NAME}" "${tmpdir}/${SUMS_NAME}"; then
  echo "Failed to download ${SUMS_NAME}" >&2
  exit 1
fi

if ! grep " ${LINUX_ASSET}$" "${tmpdir}/${SUMS_NAME}" | (cd "$tmpdir" && sha256sum -c -); then
  echo "Checksum verification failed for ${LINUX_ASSET}" >&2
  exit 1
fi

mkdir -p "$tmpdir/extract"
tar -C "$tmpdir/extract" -xzf "${tmpdir}/${LINUX_ASSET}"

installer=""
if [[ -f "$tmpdir/extract/scripts/linux/install-service.sh" ]]; then
  installer="$tmpdir/extract/scripts/linux/install-service.sh"
fi

if [[ ! -f "$tmpdir/extract/constitute-gateway" ]]; then
  echo "Release artifact missing constitute-gateway binary" >&2
  exit 1
fi
if [[ -z "$installer" ]]; then
  echo "Release artifact missing Linux installer script" >&2
  exit 1
fi

installer_args=(
  --binary "$tmpdir/extract/constitute-gateway"
  --config-template "$tmpdir/extract/config.example.json"
)
if [[ -n "$PAIR_IDENTITY" ]]; then
  installer_args+=(--pair-identity "$PAIR_IDENTITY")
fi
if [[ -n "$PAIR_CODE" ]]; then
  installer_args+=(--pair-code "$PAIR_CODE")
fi
if [[ -n "$PAIR_CODE_HASH" ]]; then
  installer_args+=(--pair-code-hash "$PAIR_CODE_HASH")
fi

skip_install=0
installed_bin="/usr/local/bin/constitute-gateway"
installed_cfg="/etc/constitute-gateway/config.json"
rollback_dir="$tmpdir/rollback"
mkdir -p "$rollback_dir"

if [[ -f "$installed_bin" ]]; then
  cp -f "$installed_bin" "$rollback_dir/constitute-gateway.prev"
fi
if [[ -f "$installed_cfg" ]]; then
  cp -f "$installed_cfg" "$rollback_dir/config.prev.json"
fi

rollback_install() {
  echo "Update failed; attempting rollback..." >&2
  if [[ -f "$rollback_dir/constitute-gateway.prev" ]]; then
    run_sudo install -m 0755 "$rollback_dir/constitute-gateway.prev" "$installed_bin" || true
  fi
  if [[ -f "$rollback_dir/config.prev.json" ]]; then
    run_sudo install -m 0644 "$rollback_dir/config.prev.json" "$installed_cfg" || true
  fi
  if command -v systemctl >/dev/null 2>&1 && systemctl list-unit-files | grep -q '^constitute-gateway\.service'; then
    run_sudo systemctl restart constitute-gateway.service || true
  fi
}

if [[ -z "$PAIR_IDENTITY" && -z "$PAIR_CODE" && -z "$PAIR_CODE_HASH" && -f "$installed_bin" ]]; then
  if command -v systemctl >/dev/null 2>&1 && systemctl list-unit-files | grep -q '^constitute-gateway\.service'; then
    current_hash="$(sha256sum "$installed_bin" | awk '{print $1}')"
    incoming_hash="$(sha256sum "$tmpdir/extract/constitute-gateway" | awk '{print $1}')"
    if [[ "$current_hash" == "$incoming_hash" ]]; then
      skip_install=1
      echo "No binary change detected; skipping reinstall/restart."
    fi
  fi
fi

if [[ "$skip_install" -eq 0 ]]; then
  if ! bash "$installer" "${installer_args[@]}"; then
    rollback_install
    exit 1
  fi

  if command -v systemctl >/dev/null 2>&1 && systemctl list-unit-files | grep -q '^constitute-gateway\.service'; then
    if ! run_sudo systemctl is-active --quiet constitute-gateway.service; then
      rollback_install
      echo "Gateway service is not active after update." >&2
      exit 1
    fi
  fi
fi

patch_release_metadata "release" "latest" ""

echo "Install/update complete: constitute-gateway"

if [[ "$SETUP_TIMER" -eq 1 ]]; then
  require_cmd systemctl
  setup_update_timer
  echo "Auto-update timer configured: ${TIMER_UNIT} (interval: ${TIMER_INTERVAL})"
fi