name: constitute-gateway
base: core22
version: '0.1.0'
summary: Constitute native gateway

description: |
  Native gateway service for Constitute. Provides discovery bootstrap and
  relay services for browser peers on constrained devices and servers.

grade: devel
confinement: strict

apps:
  gateway:
    command: bin/constitute-gateway
    daemon: simple
    restart-condition: on-failure
    restart-delay: 5s
    start-timeout: 30s
    stop-timeout: 10s
    plugs:
      - network
      - network-bind

parts:
  gateway:
    plugin: rust
    source: .
    rust-path: ["."]
    build-packages:
      - pkg-config
    build-environment:
      - CARGO_FEATURES: "platform-linux"
